# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-11 12:02
from __future__ import unicode_literals

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('reference', '0022_academicyear_academicyearadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('fax', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('esb_id', models.IntegerField(unique=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='true_entity', to='reference.Country')),
            ],
            options={
                'verbose_name_plural': 'entities',
                'verbose_name': 'entity',
            },
        ),
        migrations.CreateModel(
            name='EntityYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('acronym', models.CharField(db_index=True, max_length=20, verbose_name='acronym')),
                ('entity_type', models.CharField(blank=True, choices=[
                    ('SECTOR', 'Sector'), ('FACULTY', 'Faculty'),
                    ('SCHOOL', 'School'), ('INSTITUTE', 'Institute'),
                    ('POLE', 'Pole'),
                    ('DOCTORAL_COMMISSION', 'Doctoral commission'),
                    ('PLATFORM', 'Platform'),
                    ('LOGISTICS_ENTITY', 'Logistics entity')
                ], max_length=50, verbose_name='Type')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos', verbose_name='logo')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('academic_year',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities',
                                   to='reference.AcademicYear', verbose_name='academic year')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Entity')),
                ('parent',
                 mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='children', to='entity.EntityYear', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'Annualized entities',
                'verbose_name': 'Annualized entity',
            },
        ),
        migrations.AlterUniqueTogether(
            name='entityyear',
            unique_together={('entity', 'academic_year')},
        ),
    ]
