# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-07 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0022_academicyear_academicyearadmin'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('acronym', models.CharField(db_index=True, max_length=20)),
                ('entity_type', models.CharField(blank=True, choices=[('SECTOR', 'Sector'), ('FACULTY', 'Faculty'), ('SCHOOL', 'School'), ('INSTITUTE', 'Institute'), ('POLE', 'Pole'), ('DOCTORAL_COMMISSION', 'Doctoral commission'), ('PLATFORM', 'Platform'), ('LOGISTICS_ENTITY', 'Logistics entity')], db_index=True, max_length=50, verbose_name='Type')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos', verbose_name='logo')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='reference.AcademicYear', verbose_name='academic year')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Entity')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='entity.EntityYear')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='entityyear',
            unique_together=set([('entity', 'academic_year')]),
        ),
    ]
